import pandas as pd
from pandasql import sqldf
import matplotlib.pyplot as plt

#load the CSV files into pandas DataFrames
pizzas_df=pd.read_csv(r"D:\data_and_cloud_analytics\tables\pizzas.csv")
orders_df=pd.read_csv(r"D:\data_and_cloud_analytics\tables\orders.csv")
order_details_df=pd.read_csv(r"D:\data_and_cloud_analytics\tables\order_details.csv")

#clean the date column in orders_df and handle potential issues
orders_df['date']=pd.to_datetime(orders_df['date'], format='%m/%d/%Y', errors='coerce')
orders_df=orders_df.dropna(subset=['date'])  # Drop rows with invalid dates

#add a column for the day of the week to the orders_df
orders_df['day_of_week']=orders_df['date'].dt.day_name()

#define the SQL query to calculate revenue for each day of the week
query = """
        SELECT o.day_of_week, COALESCE(SUM(od.quantity*p.price), 0) AS revenue
        FROM order_details_df od
        LEFT JOIN pizzas_df p ON p.pizza_id=od.pizza_id
        LEFT JOIN orders_df o ON od.order_id=o.order_id
        GROUP BY o.day_of_week
        ORDER BY revenue DESC
        """

#execute the query using pandasql
result=sqldf(query, locals())

#plot the results
plt.figure(figsize=(10, 6))
plt.bar(result['day_of_week'], result['revenue'], color='purple')
plt.title('Revenue Generated by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Revenue')
plt.grid(True)
plt.show()

#print the result for reference
print(result)
